# Generated by Django 4.1.2 on 2022-11-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.TextField(blank=True, max_length=100)),
                ('imgURL', models.SlugField(max_length=200)),
                ('bio', models.TextField(blank=True, max_length=300, null=True)),
                ('twitter', models.SlugField(max_length=200)),
                ('linkedin', models.SlugField(max_length=200)),
                ('youtube', models.SlugField(max_length=200)),
                ('github', models.SlugField(max_length=200)),
            ],
        ),
    ]
